### ISSUE TITLE
Class inheritance diagram displayed incorrectly in the docs

### ISSUE THREAD

**Issue by meandmytram** [XanaduAI/flamingpy#45]
### Before posting a bug report

- [X] I have searched existing GitHub issues and documentation to make sure the issue and relevant resolutions do not already exist.

### Expected behavior

In the documentation, one expects seeing the class inhertance diagram for the [`codes` module](https://flamingpy.readthedocs.io/en/latest/source/fp.codes.html).

### Actual buggy behavior

What I see is the following.
<img width="1161" alt="Screen Shot 2022-05-18 at 13 24 57" src="https://user-images.githubusercontent.com/34054905/169104590-083101d8-def0-48e0-973a-c7b824912c93.png">

### How to reproduce

Go to https://flamingpy.readthedocs.io/en/latest/source/fp.codes.html.

### System information

```shell
N/A
```

**Comment by ilan-tz** [comment]
Thanks for catching this, @meandmytram! 😄 One of our team members is on it.
