### ISSUE TITLE
Add more natural choice of periodic boundaries

### ISSUE THREAD

**Issue by soosub** [XanaduAI/flamingpy#52]
Currently, the "periodic" setting in SurfaceCode means periodic in all three directions. This is useful but unnatural. The setting should be changed to "all_periodic" and a new setting ("periodic") added with boundaries that are periodic in x and y but not z. This will require changes to RHG_graph and various SurfaceCode methods, as well as the check_correction function in decoder.py.

**Comment by ilan-tz** [comment]
This task temporarily transferred to Sebastian.
