### ISSUE TITLE
Change scope of `docformatter` and `black` 👁️ 

### ISSUE THREAD

**Issue by soosub** [XanaduAI/flamingpy#66]
_This issue has been tagged for a bounty during [unitaryHACK](https://unitaryfund.github.io/unitaryhack/participating-projects.html)_.

## Tasks
1. Include all Python files in this repository to be checked by `docformatter`
2. Include the `doc` directory in the scope of the `black` formatter.

## Explanation
Currently, we only check some `.py` files, namely `flamingpy/*/*.py`, with `docformatter` whereas it makes sense to check all Python files, including test files and files like `setup.py`. This will improve the quality of the docstrings and the code in general, making it easier to use and develop.

For part 1 of the task, you effectively have to change `python -m docformatter --in-place  flamingpy/*/*.py` to `python -m docformatter --in-place  **.py` in the CI checks. For part 2, make sure this does not break `doc` workflows!

## Submission
To work on this task, simply fork the repository. Please also comment in this thread to communicate that you are working on this issue. Once ready, you can open a PR that we will review and hopefully merge making you an official FlamingPy contributor 🔥 🥧 

Good luck 🍀 

\- Joost

**Comment by nariman87** [comment]
`black` runs can also include doc/ dir.

**Comment by nariman87** [comment]
@soosub is in charge of adding details for UnitaryHack.

**Comment by WingCode** [comment]
@soosub I would like to work on this issue. Could you kindly assign it to me?

**Comment by ilan-tz** [comment]
@WingCode since this is a unitaryHACK issue we won't be assigning it, but we see your PR, so thanks for that!
