### ISSUE TITLE
Make `EGraph` visualizations more interactive using Plotly 🎨 

### ISSUE THREAD

**Issue by soosub** [XanaduAI/flamingpy#72]
_This issue has been tagged for a bounty during [unitaryHACK](https://unitaryhack.dev/projects/flamingpy/)_.

## Tasks
- At the moment, we use `matplotlib` for our visualization module. However, sometimes different visualization back-ends work nicer. For example, the interactivity of the graph state plots in `matplotlib` is not great. The idea of this task is to improve this plot interactivity by adding [`plotly`](https://plotly.com/python/) functionality. In particular, the task is to implement a method analogous to [`EGraph.draw`](https://github.com/XanaduAI/flamingpy/blob/main/flamingpy/utils/viz.py) that uses a `plotly` [3D scatter plot](https://plotly.com/python/3d-scatter-plots/).  

## Submission
To work on this task, simply fork the repository. Please also comment in the chat to communicate that you are working on this issue. Once ready, you can open a PR that we will review and hopefully merge, making you an official FlamingPy contributor 🔥 🥧 

Good luck 🍀 

\- Joost

**Comment by Avhijit-codeboy** [comment]
I would like to start working on this issue.

**Comment by ilan-tz** [comment]
Go ahead, @Avhijit-codeboy ! Thanks!

**Comment by Avhijit-codeboy** [comment]
Thanks @ilan-tz !

**Comment by Avhijit-codeboy** [comment]
I think I'm close to it. Interactivity is working fine, need to figure out info and color scheme according to inputs.
![image](https://user-images.githubusercontent.com/41890388/173186987-8d3aafa4-71ed-4174-8647-27ce043b152b.png)

**Comment by Avhijit-codeboy** [comment]
I think I'm close to it. Interactivity is working fine, need to figure out info and color scheme according to inputs

https://user-images.githubusercontent.com/41890388/173187187-c8af6914-9ba8-4071-9a22-2a0b79b553b0.mp4

.

**Comment by soosub** [comment]
Already starts to look good @Avhijit-codeboy 😍 For testing I would recommend using the `graph` attribute of a [`SurfaceCode`](https://github.com/XanaduAI/flamingpy/blob/main/flamingpy/codes/surface_code.py#L227) object (generated with the [`RHG_Graph`](https://github.com/XanaduAI/flamingpy/blob/main/flamingpy/codes/surface_code.py#L105) function) with a small code distance.

Moreover, the aim for the plotly visualization is to be relatively close to the matplotlib one. In particular, the shown information (axes, labels, legend) should remain the same. Additionally, we need the ability to draw the nodes with different colours.

**Comment by soosub** [comment]
Example
```
from flamingpy.codes import SurfaceCode
from flamingpy.codes.graphs import EGraph

code = SurfaceCode(2)
code.draw()
```
![image](https://user-images.githubusercontent.com/44366402/173204055-1290135a-4588-464e-9605-5b6fed86326a.png)


You can also directly access the graph object
```
graph = code.graph
graph.draw()
```
![image](https://user-images.githubusercontent.com/44366402/173204061-42a82fef-efc7-444f-ad21-6d68bcb38608.png)

**Comment by Avhijit-codeboy** [comment]
Thanks for the inputs @soosub! Will integrate these specifications soon.

**Comment by Avhijit-codeboy** [comment]
Hi @soosub . Can you please assign me this issue? I might be pushing the changes by tonight or tomorrow EOD.

**Comment by soosub** [comment]
Hey @Avhijit-codeboy! You can open a draft PR and link it to this issue by including `closes #72` in the PR description. Once ready, you can open it so we can start to review 👍🏼

**Comment by Avhijit-codeboy** [comment]
Fair enough!

**Comment by arthurfaria** [comment]
Hi, I would also be interested in it. Is this task finished already?
