### ISSUE TITLE
Add tests to improve code coverage of `viz` module 🧪

### ISSUE THREAD

**Issue by sduquemesa** [XanaduAI/flamingpy#74]
_This issue has been tagged for a bounty during [unitaryHACK](https://unitaryhack.dev/projects/flamingpy/)_.

## Tasks

- Create a new set of unit tests (potentially in [`test_viz.py`](https://github.com/XanaduAI/flamingpy/blob/main/tests/unit/test_viz.py)) that covers all possible configuration options of the functions on the `viz` module. To see the current coverage of the module check [codecov](https://app.codecov.io/gh/XanaduAI/flamingpy/blob/main/flamingpy/utils/viz.py).

## Explanation

The [`viz`](https://github.com/XanaduAI/flamingpy/blob/main/flamingpy/utils/viz.py) utility module contains helper functions to draw various graphs and generate plots using Matplotlib. This module provides several ways to personalize and configure the resulting figures via the use of function parameters.

The complete set of possible configurations has not been added to the FlamingPy test suite.

## Requirements

- Instead of using image comparison to evaluate the output of the functions of the module I would instead recommend using [mocking](https://docs.pytest.org/en/7.1.x/how-to/monkeypatch.html) to mock `matplotlib`'s methods and check that appropriate calls with appropriate arguments are passed to those (mocked) methods.
- The implementation of this test should cover >99% of the `viz` module.

**Comment by nariman87** [comment]
We can archive this till we work on different backends or next HACK competitions.
