### ISSUE TITLE
[Discussion] Add tests to improve FlamingPy's test suite coverage to >99%

### ISSUE THREAD

**Issue by sduquemesa** [XanaduAI/flamingpy#75]
To bring FlamingPy's test suite coverage >99% is imperative to add tests to the following modules and packages (current coverage in parenthesis):

- `flamingpy/codes/surface_code.py` (97.31%)
- `flamingpy/codes/graphs/egraph.py` (94.57%)
- `flamingpy/codes/graphs/stabilizer_graph.py` (96.65%)
- `flamingpy/codes/cv` (93.32%)

Most of the additions are related to untested edge cases. 

This issue relates to https://github.com/XanaduAI/flamingpy/issues/74

**Comment by nariman87** [comment]
Let's create separate tickets for each individual test suite.
