### ISSUE TITLE
Make sure non-Xanadu links open in a new page

### ISSUE THREAD

**Issue by soosub** [XanaduAI/flamingpy#81]
To make navigating the docs website nicer, it would be good to open non-Xanadu website links (in e.g. the tutorials) on a new tab/page rather than making the user leave Xanadu sites.

**Comment by nariman87** [comment]
@soosub, if you prefer I am happy to do this as part of my regular docs maintenance. However, feel free to go for it if you have existing local work.

**Comment by soosub** [comment]
Yes please 👍🏼 @nariman87
